### ISSUE TITLE
Add `Ceph Snapshot` support

### ISSUE THREAD

**Issue by lukasfrank** [onmetal/cephlet#26]
# Summary
The `spec/image` defined in the `Volume` is being populated from scratch on every following request (assuming the same image reference). This behaviour creates unnecessary traffic and uses extra disk space. The `ceph snapshot` mechanism can be used to populate an image as an overlay from an already existing image.   

reference: https://docs.ceph.com/en/quincy/rbd/rbd-snapshot/

## Basic example

Creating the following two volumes will starte the population and downloads the `test-image:v1.0.0` two times and stores it in the storage cluster. 

```
apiVersion: storage.api.onmetal.de/v1alpha1
kind: Volume
metadata:
  name: vol-a
spec:
  image: test-image:v1.0.0
  ...
```

```
apiVersion: storage.api.onmetal.de/v1alpha1
kind: Volume
metadata:
  name: vol-b
spec:
  image: test-image:v1.0.0
  ...
```

## Motivation

The volume controller can be enhanced that in the customers `ceph namespace` a *base image* for every `image+tag` combination is being created. A snapshot from the image will be taken in order to create the requested `Volume`. 

The `PVC` of the originally created `Volume` will use the `Snapshot` as data source:
```
 dataSource:
    name: rbd-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

Under the hood `Rook` ensures that ceph is being configured in a proper way: https://rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/

This mechanism reduces the load time for the image population as well as the used storage. 

Steps of the `Volume` controller: 
- create customer `VolumeSnapshotClass` 
- check if image snapshot is there
    -  if yes: create pvc with snapshot as datasource
    - if no: 
        - create pvc with populator as datasource 
        - create snapshot of *base* image

Result: 
A customer it *own* images in his ceph namespace once. For every further image a snapshot will be created.
