### ISSUE TITLE
Not empty `Volume` can't be encrypted

### ISSUE THREAD

**Issue by lukasfrank** [onmetal/cephlet#261]
**Describe the bug**
If a `Volume` references an image the `Volume` can't be encrypted. 

```
{"imageId": "505323310729f021ec9e940ba9e345109fb200bcb46730d706ff716ed9603e1", "error": "failed to set encryption header: failed to set encryption format: rbd: ret=-95, Operation not supported"}
github.com/onmetal/cephlet/pkg/controllers.(*ImageReconciler).
```

Investigation needed to check expected behaviour.

**To Reproduce**

```
metadata:
  name: encryption-test
spec:
  image: ghcr.io/onmetal/onmetal-image/gardenlinux:rootfs-dev-20230223
  volumeClassRef:
    name: general-purpose
  encryption:
    secretRef:
      name: encryption-key-secret
  resources:
    storage: 5Gi
```
